### ISSUE TITLE
Python error: ImportError: cannot import name connection 

### ISSUE THREAD

**Issue by lorex82** [Geolicious/flickr2qgis#3]
Python error at the installation on ubuntu 14.04 (32 and 64 bit) with qgis 2.8.6, 2.12, and 2.14 (after installe flickr api).

![flickr2qgis_error](https://cloud.githubusercontent.com/assets/17469189/13393486/0c3a1d76-dee2-11e5-92e0-67f5f4885c9d.jpg)

Couldn't load plugin flickr2qgis due to an error when calling its classFactory() method 

ImportError: cannot import name connection 
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/qgis/utils.py", line 306, in startPlugin
    plugins[packageName] = package.classFactory(iface)
  File "/home/lorex/.qgis2/python/plugins/flickr2qgis/**init**.py", line 34, in classFactory
    from .flickr2qgis import flickr2qgis
  File "/usr/lib/python2.7/dist-packages/qgis/utils.py", line 572, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "/home/lorex/.qgis2/python/plugins/flickr2qgis/flickr2qgis.py", line 33, in 
    import flickrapi
  File "/usr/lib/python2.7/dist-packages/qgis/utils.py", line 572, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "build/bdist.linux-x86_64/egg/flickrapi/__init__.py", line 52, in 
  File "/usr/lib/python2.7/dist-packages/qgis/utils.py", line 572, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "build/bdist.linux-x86_64/egg/flickrapi/core.py", line 13, in 
  File "/usr/lib/python2.7/dist-packages/qgis/utils.py", line 572, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "build/bdist.linux-x86_64/egg/flickrapi/tokencache.py", line 10, in 
  File "/usr/lib/python2.7/dist-packages/qgis/utils.py", line 572, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "build/bdist.linux-x86_64/egg/flickrapi/auth.py", line 23, in 
  File "/usr/lib/python2.7/dist-packages/qgis/utils.py", line 572, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "build/bdist.linux-x86_64/egg/requests_toolbelt/__init__.py", line 12, in 
  File "/usr/lib/python2.7/dist-packages/qgis/utils.py", line 572, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "build/bdist.linux-x86_64/egg/requests_toolbelt/adapters/__init__.py", line 12, in 
  File "/usr/lib/python2.7/dist-packages/qgis/utils.py", line 572, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "build/bdist.linux-x86_64/egg/requests_toolbelt/adapters/ssl.py", line 16, in 
  File "/usr/lib/python2.7/dist-packages/qgis/utils.py", line 572, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "build/bdist.linux-x86_64/egg/requests_toolbelt/_compat.py", line 22, in 
ImportError: cannot import name connection

Python version: 2.7.6 (default, Jun 22 2015, 18:01:27) [GCC 4.8.2] 
QGIS version: 2.14.0-Essen Essen, exported 

Python Path:
/home/lorex/.qgis2/python/plugins/processing
/usr/share/qgis/python
/home/lorex/.qgis2/python
/home/lorex/.qgis2/python/plugins
/usr/share/qgis/python/plugins
/usr/local/lib/python2.7/dist-packages/flickrapi-2.1.2-py2.7.egg
/usr/local/lib/python2.7/dist-packages/requests_toolbelt-0.6.0-py2.7.egg
/usr/local/lib/python2.7/dist-packages/requests_oauthlib-0.6.1-py2.7.egg
/usr/local/lib/python2.7/dist-packages/oauthlib-1.0.3-py2.7.egg
/usr/lib/python2.7
/usr/lib/python2.7/plat-x86_64-linux-gnu
/usr/lib/python2.7/lib-tk
/usr/lib/python2.7/lib-old
/usr/lib/python2.7/lib-dynload
/usr/local/lib/python2.7/dist-packages
/usr/lib/python2.7/dist-packages
/usr/lib/python2.7/dist-packages/PILcompat
/usr/lib/python2.7/dist-packages/gst-0.10
/usr/lib/python2.7/dist-packages/gtk-2.0
/usr/lib/pymodules/python2.7
/usr/lib/python2.7/dist-packages/ubuntu-sso-client
/usr/lib/python2.7/dist-packages/wx-2.8-gtk2-unicode
/home/lorex/.qgis2//python
/usr/share/qgis/python/plugins/fTools/tools

**Comment by riccardoklinger** [comment]
please open the python command tool and try 
`import flickrapi`
what is the result?

**Comment by lorex82** [comment]
Python Console
Use iface to access QGIS API interface or Type help(iface) for more info
import flickrapi
Traceback (most recent call last):
  File "<input>", line 1, in <module>
  File "/usr/lib/python2.7/dist-packages/qgis/utils.py", line 572, in
_import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "build/bdist.linux-x86_64/egg/flickrapi/__init__.py", line 52, in
<module>
  File "/usr/lib/python2.7/dist-packages/qgis/utils.py", line 572, in
_import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "build/bdist.linux-x86_64/egg/flickrapi/core.py", line 13, in
<module>
  File "/usr/lib/python2.7/dist-packages/qgis/utils.py", line 572, in
_import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "build/bdist.linux-x86_64/egg/flickrapi/tokencache.py", line 10, in
<module>
  File "/usr/lib/python2.7/dist-packages/qgis/utils.py", line 572, in
_import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "build/bdist.linux-x86_64/egg/flickrapi/auth.py", line 23, in
<module>
  File "/usr/lib/python2.7/dist-packages/qgis/utils.py", line 572, in
_import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "build/bdist.linux-x86_64/egg/requests_toolbelt/__init__.py", line
12, in <module>
  File "/usr/lib/python2.7/dist-packages/qgis/utils.py", line 572, in
_import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File
"build/bdist.linux-x86_64/egg/requests_toolbelt/adapters/__init__.py", line
12, in <module>
  File "/usr/lib/python2.7/dist-packages/qgis/utils.py", line 572, in
_import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "build/bdist.linux-x86_64/egg/requests_toolbelt/adapters/ssl.py",
line 16, in <module>
  File "/usr/lib/python2.7/dist-packages/qgis/utils.py", line 572, in
_import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "build/bdist.linux-x86_64/egg/requests_toolbelt/_compat.py", line
22, in <module>
ImportError: cannot import name connection

Thanks,
Lorenzo

2016-02-29 12:51 GMT+01:00 Riccardo Klinger notifications@github.com:

**Comment by lorex82** [comment]
The problem is only with ubuntu. on Debian 8 qgis 2.14 and fedora 23 qgis 2.10, plugin work fine.

**Comment by riccardoklinger** [comment]
Hi Lorenzo. This seems to be not a problem related to the flickr2qgis plugin. It seems like flickrapi is not installed correctly on your Ubuntu system(s). 
With typing: 
`import flickrapi`
you test the functionality of importing a module into qgis. this is independent from the plugin.

**Comment by riccardoklinger** [comment]
I've now the same problem. installed flickrapi and tried to import it in a normal python environment without the QGIS "overhead".
I've created an issue for flickrapi:
https://bitbucket.org/sybren/flickrapi/issues/64/cannot-import-flickrapi

**Comment by riccardoklinger** [comment]
on Ubuntu I solved this issue with 

```
sudo pip install --upgrade pip
sudo pip install requests --upgrade
```

@lorex82 can you try it as well?

**Comment by lorex82** [comment]
Perfect! Now ubuntu 14.04 it's ok! 
I just added this command
`apt-get install python-pip`
Thank you!!!
